server:
  port: 8088
  error:    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
custom:
  siteName: meetInHere
  siteMainUri: https://meetInHere.com/
  logoText: MeetInHere
  emailFrom: no-reply@meetInHere.com
  emailFromName: meetInHere  
spring:
  profiles:    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password: caslfrokflgzpwan
    properties:      mail:
        smtp:
          auth: true
          starttls:
            enable:  true
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/temp
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/meet?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
mybatis:
  type-aliases-package: com.sbs.meet.dto
    
